services:
  api:
    image: ghcr.io/V4S-CZ/www-backend:latest
    # build:
    #  context: .
    #  dockerfile: ./Dockerfile
    #  args:
    #    - http_proxy
    #    - https_proxy
    #    - no_proxy
    restart: always
    ports:
      - "8001:80"
    # volumes:
    environment:
      TZ: Europe/Prague
    stdin_open: true  # -i
    tty: true         # -t
